---
output: html_fragment
---

```{r include = FALSE}
# Simple function to retrieve local icons
mySvg = function(name, height = 1, align = "-0.1em") {
  shiny::tags$img(src = sprintf("../static_icons/%s.svg", name),
                  style = sprintf("height:%fem; width:auto; vertical-align:%s;", height, align))
  
}
```

# Pedigree builder

The pedigree builder lets you create and edit the reference families in your DVI case. </br> 
This is where you tell the program ___who is missing___ and their relation to the ___reference individuals___.

#### 1. Edit the pedigree

* **Select** a pedigree member by clicking on it so that it turns blue.
* **Click** an appropriate button, for instance:
    - `Child` to add a child
    - <code>`r mySvg("arrow-left", align = "-0.2em")`Sib</code> to add a sibling to the left
    - `Remove` to remove the individual and its descendants
* To **deselect** individuals, either click on them again, or use `r mySvg("hand-pointer-strikethrough", height = 1.2)` to deselect all.
* Click <code style="background-color:orange; font-weight:bolder; padding:0 5px">UNDO</code> to take back the last action,
or <code style="background-color:orangered; font-weight:bolder; padding:0 5px">RESET</code> to start over.

#### 2. Missing persons

* **Select** one or several pedigree members.
* **Click** the `r mySvg("circle-dot-red", height = 1.1)` button to mark them as missing, or the open circle to revert.
* **Double-click** on the pedigree symbol to edit the name of a missing person.

*Result:* The missing pedigree members appear with a red symbol.

#### 3. Reference individuals

AM individuals that have not been assigned are in the *References* list.

* First **select** a pedigree member you want to link to a reference sample.
* Then **click** the corresponding entry in the *References* list.
* To **unassign** references, select them in the pedigree and click the arrow
`r mySvg("circle-left", height = 1.2, align = "-0.1em")`.

*Result:* Assigned references appear with hatched symbols in the pedigree.  


#### 4. Save

Click `Save` to save the pedigree and go back to the main window.
